//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkProtectionDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttachedFile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AttachedFile()
        {
            this.BriefingAttachedFile = new HashSet<BriefingAttachedFile>();
            this.InstructionBlitzFile = new HashSet<InstructionBlitzFile>();
            this.InstructionFile = new HashSet<InstructionFile>();
            this.SurveyAttachedFile = new HashSet<SurveyAttachedFile>();
        }
    
        public System.Guid Guid { get; set; }
        public string Name { get; set; }
        public string Path { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> FolderId { get; set; }
    
        public virtual AttachedFileFolder AttachedFileFolder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BriefingAttachedFile> BriefingAttachedFile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstructionBlitzFile> InstructionBlitzFile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstructionFile> InstructionFile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SurveyAttachedFile> SurveyAttachedFile { get; set; }
    }
}
