//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkProtectionDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Briefing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Briefing()
        {
            this.BriefingAttachedFile = new HashSet<BriefingAttachedFile>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public System.Guid PatientGuid { get; set; }
        public Nullable<System.Guid> InstructionGuid { get; set; }
        public int StatusId { get; set; }
        public int TimeSeconds { get; set; }
        public System.Guid DeviceGuid { get; set; }
        public Nullable<int> InstructionVersion { get; set; }
        public int InstructionType { get; set; }
        public Nullable<System.Guid> BlitzInstructionGuid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BriefingAttachedFile> BriefingAttachedFile { get; set; }
    }
}
