//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkProtectionDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BriefingReport
    {
        public int Id { get; set; }
        public int PeriodType { get; set; }
        public int Status { get; set; }
        public string PrintFormPath { get; set; }
        public string MailTo { get; set; }
        public string Comment { get; set; }
        public Nullable<int> SettingsId { get; set; }
        public System.DateTime DateFrom { get; set; }
        public System.DateTime DateTo { get; set; }
    }
}
