//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkProtectionDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstructionSettings
    {
        public int Id { get; set; }
        public int PeriodTimeValue { get; set; }
        public int PeriodTimeType { get; set; }
        public int NewVersionTimeValue { get; set; }
        public int NewVersionTimeType { get; set; }
        public int InactiveTimeValue { get; set; }
        public int InactiveTimeType { get; set; }
        public string DayColors { get; set; }
        public string BlitzDayColors { get; set; }
    }
}
