//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkProtectionDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstructionInfo
    {
        public System.Guid Guid { get; set; }
        public int Id { get; set; }
        public int CurrentVersion { get; set; }
        public System.Guid RecordGuid { get; set; }
        public int RecordVersion { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<int> Version { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Comment { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string CategoryName { get; set; }
        public string SearchCode { get; set; }
        public string SearchName { get; set; }
        public Nullable<int> FileCount { get; set; }
        public bool IsArchive { get; set; }
    }
}
