//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkProtectionDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstructionBlitzFile
    {
        public int Id { get; set; }
        public System.Guid InstructionBlitzGuid { get; set; }
        public System.Guid FileGuid { get; set; }
    
        public virtual AttachedFile AttachedFile { get; set; }
    }
}
