//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkProtectionDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instruction
    {
        public int VersionId { get; set; }
        public System.Guid RecordGuid { get; set; }
        public int Number { get; set; }
        public Nullable<int> InstructionVersion { get; set; }
        public Nullable<System.DateTime> InstructionDate { get; set; }
        public string InstructionName { get; set; }
        public string InstructionCode { get; set; }
        public string InstructionComment { get; set; }
        public string InstructionCategory { get; set; }
        public Nullable<int> InstructionCategoryId { get; set; }
    }
}
