//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkProtectionDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientFullInfo
    {
        public System.Guid Guid { get; set; }
        public Nullable<System.Guid> RecordGuid { get; set; }
        public Nullable<int> Version { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string FullName { get; set; }
        public string ShortName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<int> Years { get; set; }
        public string SEX { get; set; }
        public string SeriyaPolisa { get; set; }
        public string NomerPolis { get; set; }
        public string InsuranceCompany { get; set; }
        public Nullable<System.DateTime> InsuranceDateFrom { get; set; }
        public Nullable<System.DateTime> InsuranceDateTo { get; set; }
        public string AttachmentOrganisation { get; set; }
        public string SECTOR { get; set; }
        public string Code { get; set; }
        public string Comment { get; set; }
        public string MedCardNum { get; set; }
        public string NumberAmb { get; set; }
        public string SNILS { get; set; }
        public Nullable<bool> LgotDrug { get; set; }
        public string JobTabNumber { get; set; }
        public string HomePhoneNumber { get; set; }
        public string MobilePhoneNumber { get; set; }
        public Nullable<int> ChatId { get; set; }
        public string PlaceOfJob { get; set; }
        public Nullable<System.Guid> OrganisationGuid { get; set; }
        public string Post { get; set; }
        public string Profession { get; set; }
        public string WorkPhoneNumber { get; set; }
        public string JobComment { get; set; }
        public string JobFactory { get; set; }
        public string JobSection { get; set; }
        public string JobDepartment { get; set; }
        public string JobCharacter { get; set; }
        public string JobCondition { get; set; }
        public Nullable<System.DateTime> JobBeginDate { get; set; }
        public Nullable<System.DateTime> JobEndDate { get; set; }
        public string PostId { get; set; }
        public string ProfessionId { get; set; }
        public string PatientLgot { get; set; }
        public string InvalGroup { get; set; }
        public string InvalOtkazOtDlo { get; set; }
        public string InvalOsvidetPodlezhit { get; set; }
        public string InvalDopZakl { get; set; }
        public string InvalReason { get; set; }
        public string InvalPredGroup { get; set; }
        public string InvalOgranichStepen { get; set; }
        public string InvalLgotCode { get; set; }
        public Nullable<System.DateTime> InvalDataOcherednogoOsvidetel { get; set; }
        public string InvalPrichinaSnyatiya { get; set; }
        public Nullable<System.DateTime> InvalDataSnyatiya { get; set; }
        public string InvalSeriya { get; set; }
        public string InvalFioVracha { get; set; }
        public string InvalPervich { get; set; }
        public string InvalVidan { get; set; }
        public Nullable<System.DateTime> InvalDataVidachi { get; set; }
        public string InvalItog { get; set; }
        public string InvalNomer { get; set; }
        public Nullable<System.DateTime> InvalDataUstanovleniya { get; set; }
        public string InvalMkbCode { get; set; }
        public string InvalComment { get; set; }
        public Nullable<System.DateTime> InvalSrok { get; set; }
        public string Login { get; set; }
        public Nullable<int> UserId { get; set; }
        public string PaspKemVidan { get; set; }
        public string PaspSeries { get; set; }
        public string PaspNumber { get; set; }
        public Nullable<System.DateTime> PaspDataVidachi { get; set; }
        public string IdentityDocument { get; set; }
        public Nullable<System.DateTime> PasportFromDate { get; set; }
        public Nullable<System.DateTime> PasportToDate { get; set; }
        public string DepartmentCode { get; set; }
        public string EMAIL { get; set; }
        public string InfoSource { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsArchive { get; set; }
        public Nullable<int> PaymentMethodId { get; set; }
        public string PaymentMethod { get; set; }
        public string PersonelNumber { get; set; }
        public int Id { get; set; }
        public string SearchFirstName { get; set; }
        public string SearchLastName { get; set; }
        public string SearchMiddleName { get; set; }
        public string SearchPhone { get; set; }
        public string SearchAddress { get; set; }
        public string SearchComment { get; set; }
        public string SearchFullName { get; set; }
        public string Citizenship { get; set; }
        public Nullable<bool> NotificationSmsEnable { get; set; }
        public Nullable<bool> NotificationMailEnable { get; set; }
    }
}
