//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkProtectionDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int Id { get; set; }
        public System.Guid Guid { get; set; }
        public string SearchFirstName { get; set; }
        public string SearchLastName { get; set; }
        public string SearchMiddleName { get; set; }
        public string SearchPhone { get; set; }
        public string SearchAddress { get; set; }
        public string SearchComment { get; set; }
        public string SearchFullName { get; set; }
        public System.Guid RecordGuid { get; set; }
    
        public virtual Record Record { get; set; }
    }
}
