//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkProtectionDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientRelation
    {
        public int Id { get; set; }
        public System.Guid ParentPatientGuid { get; set; }
        public System.Guid ChieldPatientGuid { get; set; }
        public int TypeId { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public bool IsArchive { get; set; }
    
        public virtual PatientRelationType PatientRelationType { get; set; }
    }
}
