//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkProtectionDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientDactilography
    {
        public System.Guid PatientGuid { get; set; }
        public string LeftIndex { get; set; }
        public string LeftMiddle { get; set; }
        public string LeftRing { get; set; }
        public string LeftLittle { get; set; }
        public string LeftThumb { get; set; }
        public string RightIndex { get; set; }
        public string RightMiddle { get; set; }
        public string RightRing { get; set; }
        public string RightLittle { get; set; }
        public string RightThumb { get; set; }
    }
}
