//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkProtectionDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Post()
        {
            this.InstructionProfession = new HashSet<InstructionProfession>();
            this.SurveyTemplateProfession = new HashSet<SurveyTemplateProfession>();
        }
    
        public int ID { get; set; }
        public Nullable<int> P_ID { get; set; }
        public string Name { get; set; }
        public string OKPDTR { get; set; }
        public string OKZ { get; set; }
        public string KCS { get; set; }
        public string TARIFF { get; set; }
        public string ETKS { get; set; }
        public string CATEGOGY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstructionProfession> InstructionProfession { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SurveyTemplateProfession> SurveyTemplateProfession { get; set; }
    }
}
