//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkProtectionDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int VersionId { get; set; }
        public System.Guid RecordGuid { get; set; }
        public int Number { get; set; }
        public Nullable<int> QuestionCategoryId { get; set; }
        public string QuestionCode { get; set; }
        public string QuestionName { get; set; }
        public string QuestionComment { get; set; }
        public string QuestionCategory { get; set; }
        public string QuestionText { get; set; }
        public string QuestionImage { get; set; }
    }
}
