//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkProtectionDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionAnswer
    {
        public int VersionId { get; set; }
        public System.Guid RecordGuid { get; set; }
        public int Number { get; set; }
        public string AnswerComment { get; set; }
        public string AnswerCode { get; set; }
        public string AnswerCorrect { get; set; }
        public string AnswerName { get; set; }
        public Nullable<int> AnswerCorrectId { get; set; }
        public string Normativno_pravovoy_akt { get; set; }
        public string Punkt_dokumenta { get; set; }
    }
}
