//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkProtectionDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionAnswerInfo
    {
        public System.Guid QuestionGuid { get; set; }
        public int SystemNumber { get; set; }
        public System.Guid RecordGuid { get; set; }
        public int RecordVersion { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Comment { get; set; }
        public string Correct { get; set; }
        public Nullable<int> CorrectId { get; set; }
        public string LegalAct { get; set; }
        public string DocumentParagraph { get; set; }
    }
}
