//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkProtectionDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyTemplate
    {
        public int VersionId { get; set; }
        public System.Guid RecordGuid { get; set; }
        public int Number { get; set; }
        public string SurveyButtonName { get; set; }
        public string SurveyType { get; set; }
        public string SurveyComment { get; set; }
        public string SurveyName { get; set; }
        public Nullable<System.Guid> SurveyTypeDocumentGuid { get; set; }
        public Nullable<System.Guid> SurveyTypeRepeatDocumentGuid { get; set; }
    }
}
