//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkProtectionDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyReportSettingsEmployee
    {
        public int SettingsId { get; set; }
        public System.Guid EmployeeGuid { get; set; }
    
        public virtual SurveyReportSettings SurveyReportSettings { get; set; }
    }
}
