//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkProtectionDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyAnswer
    {
        public int Id { get; set; }
        public int SurveyId { get; set; }
        public System.Guid QuestionGuid { get; set; }
        public int QuestionVersionNumber { get; set; }
        public Nullable<int> SelectedAnswerNumber { get; set; }
        public int TypeId { get; set; }
    
        public virtual Survey Survey { get; set; }
    }
}
