//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkProtectionDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyTemplatePatientInfo
    {
        public System.Guid TemplateGuid { get; set; }
        public System.Guid PatientGuid { get; set; }
        public int Id { get; set; }
        public string TemplateName { get; set; }
        public string PatientName { get; set; }
    }
}
