//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkProtectionDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyTemplateInfo
    {
        public System.Guid Guid { get; set; }
        public System.Guid RecordGuid { get; set; }
        public int VersionNumber { get; set; }
        public Nullable<System.Guid> SurveyTypeDocumentGuid { get; set; }
        public Nullable<System.Guid> SurveyTypeRepeatDocumentGuid { get; set; }
        public string ButtonName { get; set; }
        public string Type { get; set; }
        public string Comment { get; set; }
        public string Name { get; set; }
    }
}
