//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkProtectionDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyReportSettings
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SurveyReportSettings()
        {
            this.SurveyReportSettingsEmployee = new HashSet<SurveyReportSettingsEmployee>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsEnable { get; set; }
        public int PeriodType { get; set; }
        public Nullable<int> CorrectPercent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SurveyReportSettingsEmployee> SurveyReportSettingsEmployee { get; set; }
    }
}
