//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkProtectionDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyType
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> DocumentGuid { get; set; }
        public Nullable<System.Guid> RepeatDocumentGuid { get; set; }
        public string SearchName { get; set; }
    }
}
