//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkProtectionDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.UserProfilePhoto = new HashSet<UserProfilePhoto>();
        }
    
        public int Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public bool IsBlocked { get; set; }
        public Nullable<bool> IsRestorePassword { get; set; }
        public string Token { get; set; }
        public bool SecondStepOfAuthentication { get; set; }
        public Nullable<System.DateTime> EndDateBlocking { get; set; }
        public Nullable<System.DateTime> SendEmailDate { get; set; }
        public Nullable<int> LastMessageNumber { get; set; }
        public string KeyForRestorePassword { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> IsTestUser { get; set; }
        public int SipId { get; set; }
        public System.Guid Guid { get; set; }
        public int TypeId { get; set; }
        public Nullable<System.Guid> GuidByDomain { get; set; }
        public string LoginByDomain { get; set; }
        public bool isPasswordUnlimited { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserProfilePhoto> UserProfilePhoto { get; set; }
    }
}
